### PR TITLE
Emotion 10

### LINKED ISSUE #813: Update to Emotion 10
As a Mineral UI consumer I would like mineral-ui to use the latest version of Emotion so that I can take advantage of new features.

_Primary benefits_
* Unblocks future React updates.  Emotion < 10 uses deprecated lifecycle methods
* New features, such as css prop, as prop, etc.
* Smaller bundle and faster performance

**AC:**

* mineral-ui works with Emotion >= v10
* Migration guide provided
* Respective documentation and examples updated

**Other considerations**

* Will need to update minimal supported React version to 16.3
* Should align mineral styling/theming API's as needed

### PR DESCRIPTION
**Pull request by brentertz**
### Description

Update to Emotion 10 and other API changes

See the [migration guide](https://github.com/mineral-ui/mineral-ui/blob/emotion-10/docs/v0-57-migration.md) for details.

**Outstanding issues:**

* https://github.com/emotion-js/emotion/issues/1105#issuecomment-457259458
* https://github.com/emotion-js/emotion/issues/1178

### Motivation and context

Closes #813
Connects #652 #765 

### Screenshots, videos, or demo, if appropriate

https://emotion-10--mineral-ui.netlify.com

### How to test

1. Try the aforementioned [demo](https://emotion-10--mineral-ui.netlify.com)
1. Try using the `css` prop and the `as` prop on different components
1. Take it for a test drive in CRA, in various browsers
1. Review updated documentation and migration guide.

_An npm package has been published with the next tag for anyone wishing to take it for a test drive locally._  `npm i mineral-ui@next`

### Types of changes

- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

See the [migration guide](https://github.com/mineral-ui/mineral-ui/blob/emotion-10/docs/v0-57-migration.md) for details.

### Checklist

* [x] Renders and functions properly in [all supported browsers](https://github.com/mineral-ui/mineral-ui#browser-support)
* [x] Automated tests written and passing
* [x] [Accessibility](http://webaim.org/intro) and [inclusivity](https://24ways.org/2016/what-the-heck-is-inclusive-design/) considered
* [x] Rendering performance (initial load time & 60fps) and [perceived performance](http://blog.teamtreehouse.com/perceived-performance) considered
* [x] Documentation created or updated
* [x] Tested in [sandbox](https://github.com/facebookincubator/create-react-app#getting-started) if new component or breaking change

### CODE REVIEW

**Comment by avetisk** [comment]
This is just awesome! When do you think this will hit the next release?

**Comment by brentertz** [comment]
Thanks @avetisk We will publish as soon as Emotion publishes a release with the fix from https://github.com/emotion-js/emotion/pull/1209

**Comment by wmonk** [comment]
Thanks @brentertz!

Was this published already? https://github.com/emotion-js/emotion/commit/41f7ba1c6b7f74cde2c6b6fd5f3333e02e2c154b

**Comment by brentertz** [comment]
Thanks for the heads up @wmonk We'll get right on it.

**Comment by wmonk** [comment]
Awesome thank you!!

**Comment by brentertz** [comment]
This update has been published and is now available on npm as `mineral-ui@0.57.0`.

**Comment by wmonk** [comment]
👍

**Pull request merged**
