### PR TITLE
[website] Add noscript.html & noscript redirect

### LINKED ISSUE #466: [Website]: Blank screen when viewed without JavaScript
As a user visiting https://mineral-ui.com with javascript disabled, I would like it to render something besides a blank screen, so that I understand what is going on.

#### AC

* https://mineral-ui.com renders a message about requiring Javascript when viewed with JavaScript disabled
* logo, disclaimer, and link to github

#### Other considerations

* Eventually we will statically render the website and this may not be as necessary.
* Suggest to add a `<noscript />` section to `index.html` and explain that JavaScript is required to view the website.
* Consider including a "meta-refresh" to another page if anything fancy is desired. e.g.  
    ```html
    <noscript>
      <meta http-equiv="refresh" content="0;url=noscript.html">
    </noscript>
    ```

### PR DESCRIPTION
**Pull request by kylegach**
### Description

_See title_

### Motivation and context

Closes #466 

### Screenshots, videos, or demo, if appropriate

https://466-noscript--mineral-ui.netlify.com/noscript.html

screen shot 2018-03-16 at 12 26 23 pm

### How to test

1. Open https://466-noscript--mineral-ui.netlify.com and confirm it loads as expected
1. Disable JS and reload that page (or any other)
1. Confirm that you're redirected to https://466-noscript--mineral-ui.netlify.com/noscript.html

### Types of changes

- Other (provide details below)

Just website stuff.

### Checklist

* [x] Renders and functions properly in [all supported browsers](https://github.com/mineral-ui/mineral-ui#browser-support)
* [x] Automated tests written and passing [n/a]
* [x] [Accessibility](http://webaim.org/intro) and [inclusivity](https://24ways.org/2016/what-the-heck-is-inclusive-design/) considered
* [x] Rendering performance (initial load time & 60fps) and [perceived performance](http://blog.teamtreehouse.com/perceived-performance) considered [n/a]
* [x] Documentation created or updated
* [x] Tested in [sandbox](https://github.com/facebookincubator/create-react-app#getting-started) if new component or breaking change [n/a]

### How does this PR make you feel?

You shall not pass!

### CODE REVIEW

**Comment by brentertz** [comment]
For future reference, do all of these miscellaneous files in public need to be there or can we move them to /images or /assets if we update the paths?  The lack of organization drives me crazy.

**Comment by kylegach** [comment]
I didn't even consider HTMLWebpackPlugin. Seems like overkill to me, especially for something that will likely rarely be touched.

I'm trying to mark that diff as equal and resolve the report, but neither action seems to take hold on the happo site?

They unfortunately need to be in the site root. :/

**Comment by kylegach** [comment]
@trotzig — I tried signing in to happo.io with both my personal and work Google accounts. Both display the UI for resolving a report, but marking it as resolved doesn't persist and has no effect on the GitHub status. I also tried multiple browsers.

Just letting you know...

**Comment by brentertz** [comment]
I think that we should at least look briefly at the HTMLWebpackPlugin as it would potentially avoid a lot of duplication.  You might also be able to import the SVG rather than copy/paste it.

**Comment by kylegach** [comment]
We looked into that plugin. It seems like what it can do (take the same output bundle and inject it into two different templates) is exactly the opposite of what we need (take different outputs and inject them into the same template). Additionally, as this is a `noscript` scenario, we need to generate the full HTML content, not just a script reference to a bundle. Neither seemed trivial to figure out, so we're shipping as-is, with the possibility of optimizing later.

**Comment by trotzig** [comment]
> @trotzig — I tried signing in to happo.io with both my personal and work Google accounts. Both display the UI for resolving a report, but marking it as resolved doesn't persist and has no effect on the GitHub status. I also tried multiple browsers.

Thanks for the bug report! I'm having a look at it.

**Comment by trotzig** [comment]
Ah, two issues here (I think): 
- Users without admin/write access to the account are able to click the buttons (since you have a public account)
- The Accept/Reject POST 401's, but since I do an optimistic update the UI makes it look like the click persisted.

I'll work on fixing both of these issues right away. 

For reference, here are the user-access settings on your account: 
screen shot 2018-03-19 at 09 04 53

I'm guessing the "Anyone signed in with an email address on the rallydev.com domain" is problematic. Perhaps you signed in with a ca.com address? Maybe we should update the domain for your account? You can also add a invite a few email addresses directly for accounts that you may sign in as.

**Comment by trotzig** [comment]
@kylegach okay, bugs are fixed - thanks for the help. Let me know if we need to do something to user access settings to simplify managing your account (adding more admins, etc).

**Comment by kylegach** [comment]
Thanks, @trotzig. Sent you an email.

**Pull request merged**
