### PR TITLE
Update to Happo v1.0

### PR DESCRIPTION
**Pull request by brentertz**
### Description

Update to Happo v1.0

### Motivation and context

This is a repost of PR #616 from an internal team member as Happo tests do not run on external PR's.  Please see #616 for further details.

### CODE REVIEW

**Comment by trotzig** [comment]
Thanks! Did you install the happo github app prior to pushing this? Nothing should break if you didn't, it's just that we won't hear anything back from Happo. 

https://github.com/apps/happo

**Comment by brentertz** [comment]
@trotzig It looks like the Happo tests ran successfully.

https://travis-ci.org/mineral-ui/mineral-ui/jobs/354295714
https://happo.io/a/14/report/e6839ecd9bd847e52459e74d9a29fd0d2dc7b80a

I believe that the PR cannot be merged until the Happo app is available and configured in GitHub, otherwise we would not get status reports in the mean time, correct?

**Comment by brentertz** [comment]
Just saw that it was available. Installing now...

**Comment by trotzig** [comment]
Ah, good.

**Comment by trotzig** [comment]
A force-push should retrigger things.

**Comment by brentertz** [comment]
Cool! 😎

**Comment by trotzig** [comment]
Nice, looks like things are working. I checked that the buttons on the report page triggers an update here as well (that's why the status changed from "No diffs." to "Resolved by henric.trotzig"). 

You can try it out yourself here: 
https://happo.io/a/14/compare/ed1cd69a2eb6d74a58a171af73bb1d6efd5d5a6f/22068e39a608f75ac800d8339289ef3289b3f405?t=deleted

**Comment by trotzig** [comment]
Thanks for being so responsive to my changes and requests. It means a lot to me to have a real project to test my updates with. And thanks for pointing/pushing me in the direction of switching to status updates instead of comments. I think it makes a lot of sense. 

I'll monitor the project for a bit to make sure things are continuing to work smoothly.

Thanks!

**Comment by brentertz** [comment]
Absolutely!  And thanks to you for providing Happo and the integration assistance.

**Comment by brentertz** [comment]
@trotzig I rebased the other open PR's and the Happo status checks look great.  I think this will be a much better workflow. 👍

**Comment by trotzig** [comment]
Yeah, I agree. Less spam, better focus. 👍

**Pull request merged**
