### PR TITLE
Update Happo

### PR DESCRIPTION
**Pull request by brentertz**
### Description

Update Happo

### Motivation and context

Take advantage of new features and fixes
* Simpler config
* Diffs run on each commit
* Help avoid issues like the one discussed in https://github.com/mineral-ui/mineral-ui/pull/812#issuecomment-452423601

### Screenshots, videos, or demo, if appropriate

https://update-happo--mineral-ui.netlify.com/

### How to test

Check that the Happo report is generated that looks as expected

### Types of changes

- Other (provide details below)
Maintenance

### Checklist

* [x] Renders and functions properly in [all supported browsers](https://github.com/mineral-ui/mineral-ui#browser-support) - **[n/a]**
* [x] Automated tests written and passing - **[n/a]**
* [x] [Accessibility](http://webaim.org/intro) and [inclusivity](https://24ways.org/2016/what-the-heck-is-inclusive-design/) considered - **[n/a]**
* [x] Rendering performance (initial load time & 60fps) and [perceived performance](http://blog.teamtreehouse.com/perceived-performance) considered - **[n/a]**
* [x] Documentation created or updated - **[n/a]**
* [x] Tested in [sandbox](https://github.com/facebookincubator/create-react-app#getting-started) if new component or breaking change - **[n/a]**

### CODE REVIEW

**Comment by brentertz** [comment]
Hi @trotzig.  Per your recommendation, I am attempting to update Happo to 3.6.  I am not quite sure however what to make of the branch failure or the diffs.  Any thoughts?

**Comment by trotzig** [comment]
Ouch, that doesn't look right. There are two issues here: 

- The HAPPO_KEY and HAPPO_SECRET env variables aren't populated for some reason, this is what's causing the [build failure](https://travis-ci.com/mineral-ui/mineral-ui/jobs/169206833). I vaguely remember this has been an issue in the past as well. I think those secrets are in .travis.yml but for some reason they're not made available to the happo-ci script. Would you mind adding these env vars in the Travis UI instead and see if that changes anything? https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

- The happo diff looks like it's related to font loading. I did make a small change (adding a font with better emoji support to the Chrome instances a while back) but that shouldn't affect you. I'm looking into this right away, at first glance it looks like your Open Sans font isn't applied/loaded but I'm not 100% sure.

**Comment by brentertz** [comment]
@trotzig Thanks for your attention.  I have added the happo keys to the travis env and kicked off a new build.

**Comment by brentertz** [comment]
@trotzig Thanks for the help.  I changed the font url to https and reintroduced happo.js with the `speedy: false option`.  The diffs are better, (e.g. The TextArea diff appears accurate), but others still show some unexpected differences.  e.g. positioning of Dropdowns/Popovers/Tooltips

**Comment by trotzig** [comment]
It looks like those diffs are the same as we saw in that other PR: https://github.com/mineral-ui/mineral-ui/pull/812#issuecomment-452467000

Since this PR has the same base commit as #812, we'll have those issues here too. 

Thanks for the patience around all this. It's pretty clear to me that there's a flaw in the current model. I've already started mitigating situations like these, but I have some further ideas on how we could improve things: 
- When a CI build is (manually) retriggered, we could ignore checking for a previous report and always generate both. I'm guessing a lot of users will try retriggering as a first step in trying to "fix" a confusing Happo build.  
- We could have a Happo setting disabling reuse of old reports. When a build is triggered, we always generate both. This would lead to slower jobs, but they'll be more consistent. 

Let me know if you have thoughts around this too!

**Comment by brentertz** [comment]
Those both sound like viable options to me.  Having an explicit way to manually regenerate the baseline, perhaps from the CLI, might also be useful.

So, is your current recommendation to just merge this PR and somehow re-baseline thereafter?

**Comment by trotzig** [comment]
Sorry, I missed this message: 
> So, is your current recommendation to just merge this PR and somehow re-baseline thereafter?

Yep!  And I see you did. 👍

**Pull request merged**
