### PR TITLE
[Website] Increase maxHeight of codeblocks

### LINKED ISSUE #477: [Website] live code box max height is too small
it just needs to be a little taller

### PR DESCRIPTION
**Pull request by kylegach**
### Description

Make sure the codeblock maxHeight fits the content of the Usage source in Getting Started.

### Motivation and context

Closes #477 

### Screenshots, videos, or demo, if appropriate

https://477-code-block-max-height--mineral-ui.netlify.com/

### How to test

1. `cd mineral-ui && npm start`
2. Go to Getting Started
3. Make sure you don't have to scroll the code block
4. Go to a component demo with a long source (MenuItem's Custom Render is good)
5. Make sure you _do_ have to scroll that code block

### Types of changes

- Other (provide details below)

Just a site thing.

### Checklist

* [x] Renders and functions properly in [all supported browsers](https://github.com/mineral-ui/mineral-ui#browser-support)
* [x] Automated tests written and passing [n/a]
* [x] [Accessibility](http://webaim.org/intro) and [inclusivity](https://24ways.org/2016/what-the-heck-is-inclusive-design/) considered
* [x] Rendering performance (initial load time & 60fps) and [perceived performance](http://blog.teamtreehouse.com/perceived-performance) considered [n/a]
* [x] Documentation created or updated [n/a]
* [x] Tested in [sandbox](https://github.com/facebookincubator/create-react-app#getting-started) if new component or breaking change [n/a]

### CODE REVIEW

**Comment by coldpour** [comment]
@kylegach this looks way better. thank you. is there any way to get the styles to be shared since they are for the same purpose?

**Comment by kylegach** [comment]
@coldpour — We could put the `max-height` rule in the prismTheme css, but then we won't have access to theme variables. I kinda like that it'll "just work" if we ever adjust the font size or line height.

**Comment by coldpour** [comment]
@kylegach yea definitely, I like that part too. But what about pulling this out into a function that takes the theme and spits out a maxHeight?

**Comment by kylegach** [comment]
@coldpour — Check the first commit, please.

I also added a second commit (will be squashed post-review) that completely removes prismTheme.css in favor of placing all of the styles in the new `getCodeBlockStyles` util (plus a few on the inline `code` selector in Markdown).

**Comment by coldpour** [comment]
@kylegach this is gorgeous! nice work sir

**Pull request merged**
