### PR TITLE
chore(website): squash floating minerals into one animated svg

### PR DESCRIPTION
**Pull request by coldpour**
### Description
put all the floating rocks in one svg and removed all the paralax stuff around it

### Motivation and context

paralax was kinda broken and janky? so this makes it better and more portable
connect #429

### Screenshots, videos, or demo, if appropriate

https://429-polish-minerals--mineral-ui.netlify.com/

### How to test

1. `cd mineral-ui && npm start`
2. Scroll down the home page

### Types of changes

Chore

### Checklist

* [ ] Renders and functions properly in [all supported browsers](https://github.com/mineral-ui/mineral-ui#browser-support)
* [ ] Automated tests written and passing
* [ ] [Accessibility](http://webaim.org/intro) and [inclusivity](https://24ways.org/2016/what-the-heck-is-inclusive-design/) considered
* [ ] Rendering performance (initial load time & 60fps) and [perceived performance](http://blog.teamtreehouse.com/perceived-performance) considered
* [ ] Documentation created or updated
* [ ] Tested in [sandbox](https://github.com/facebookincubator/create-react-app#getting-started) if new component or breaking change

### How does this PR make you feel?

aww yeas

### CODE REVIEW

**Comment by coldpour** [comment]
connect #429

**Comment by brentertz** [comment]
You can also remove `react-scroll-parallax` from `package.json`.

**Comment by brentertz** [comment]
Minerals don't animate in IE/Edge.

**Comment by brentertz** [comment]
Minerals don't show at all at smaller breakpoints.

**Comment by coldpour** [comment]
Removed react-scroll-parallax. Is IE/Edge animation a requirement?

**Pull request merged**
